---
title: "Presentations"
---
-   *Introducing `openstatsware`: Who we are and what we build together*. R/Pharma APAC Conference, 31 Oct 2024.
    -   [slides](slides/rpharma-apac-2024.html)
-   *`{mmrm}`: A Robust and Comprehensive R Package for Implementing Mixed Models for Repeated Measures*. useR! 2024, 9 Jul 2024.
    -   [slides](slides/user-2024-mmrm-jul2024.html)
-   *Introducing `openstatsware`: Who we are and what we build together*. ASA BIOP DL Webinar, 23 Feb 2024.
    -   [slides](slides/asa-biop-webinar-feb2024-quarto.html)
-   *{mmrm}: an Open Source R Package for Mixed Model Repeated Measures*. China-R Conference, 28 Nov 2023.
    -   [slides](slides/china-R-mmrm-nov2023.html)
-   *Introducing `openstatsware` and the R Package `{mmrm}`*. Lightning Session at ASA SSC Mini-Symposium, 04 Nov 2023.
    -   [slides](slides/asa-ssc-mmrm-nov2023.html)
-   *Introducing `openstatsware` and the R Package `{mmrm}`*. R/Pharma Conference, 24 Oct 2023.
    -   [slides](slides/rpharma-wg-mmrm-oct2023-quarto.html)
-   *First year of the Software Engineering working group*. Regulatory-Industry Statistics Workshop 2023, 29 Sep 2023.
    -   [slides](slides/risw-first-year-wg-sep2023-quarto.html)
-   *{mmrm}: A Robust and Comprehensive R Package for Implementing Mixed Models for Repeated Measures*. JSM, 8 Aug 2023.
    -   [slides](slides/jsm-aug2023.html)
-   *Introduction to the ASA BIOP Software Engineering Working Group and the {mmrm} Package*. R Meetup, 21 Jul 2023.
    -   [slides](slides/r-meetup-july2023.html)
-   *Workshop on Good Software Engineering Practice for R*. San Francisco bay area, 20 Jul 2023.
    -   [slides](https://openpharma.github.io/workshop-r-swe-sf/listing.html)
-   *Plugging the gaps: Lessons learned from implementing the mmrm R package*. PSI, 13 Jun 2023.
    -   [slides](slides/2023-psi-aims-london.html)
-   *{mmrm}: an Open Source R Package for Mixed Model Repeated Measures*. Pharma RUG, 31 Mar 2023.
    -   [slides](slides/pharma-rug-mmrm-mar2023.html)
-   *Workshop on Good Software Engineering Practice for R*. Shanghai, 24 Mar 2023.
    -   [slides](https://openpharma.github.io/workshop-r-swe/listing.html)
-   *Workshop on Good Software Engineering Practice for R*. BBS workshop, Basel, 10 Feb 2023.
    -   [slides](https://kkmann.github.io/workshop-r-swe/listing.html)
-   *Introducing the Software Engineering working group and {mmrm}*. R/Adoption Series Webinar, 26 Jan 2023.
    -   [slides](slides/r-adoption-jan2023.html)
-   *Introducing the Software Engineering working group: Who we are and what we build together*. R Govys Meetup, 19 Jan 2023.
    -   [slides](slides/r-govys-jan2023.html)
-   *Statistical software for continuous longitudinal endpoints: Introducing the R package `mmrm`*. Joint EFSPI & BBS virtual event - Addressing intercurrent events: Treatment policy and hypothetical strategies (day 1), 8 Dec 2022.
    -   [slides](slides/bbs-efspi-mmrm-dec2022.html)
    -   [recording](https://streamingmedia.roche.com/media/t/1_toj7v6bn) (35:00)
-   *Statistical Software Engineering 101*. Video blog series on ASA BIOP Youtube channel.
    -   Unit Testing for R Developers
        -   1: The Basics \[[slides](slides/unit_testing_basic.html), [video](https://www.youtube.com/watch?v=mfLXiP4A9CA)\]
        -   2: Advancing your skills \[[slides](slides/unit_testing_advanced.html), [video](https://www.youtube.com/watch?v=n44Lfyt-Rio)\]
